# Generated by Django 5.2.8 on 2026-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='class_label',
            field=models.CharField(blank=True, choices=[('S.1', 'S.1'), ('S.2', 'S.2'), ('S.3', 'S.3'), ('S.4', 'S.4'), ('S.5', 'S.5'), ('S.6', 'S.6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.CharField(blank=True, choices=[('S.1', 'S.1'), ('S.2', 'S.2'), ('S.3', 'S.3'), ('S.4', 'S.4'), ('S.5', 'S.5'), ('S.6', 'S.6')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('name', 'class_label')},
        ),
        migrations.RemoveField(
            model_name='stream',
            name='class_ref',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
