# Generated by Django 5.2.8 on 2026-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_class_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
