# Generated by Django 5.2.8 on 2026-05-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.CharField(blank=True, help_text='Exam index number (S.4 / S.6 only)', max_length=30, null=True),
        ),
    ]
