# Generated by Django 5.2.8 on 2026-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_district_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Ugandan', max_length=100),
        ),
    ]
