# Generated by Django 5.2.8 on 2026-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial'), ('not_paid', 'Not Paid')], default='not_paid', max_length=20),
        ),
    ]
