# Generated by Django 5.2.8 on 2026-05-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('template', models.CharField(default='modern', max_length=20)),
                ('report_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
    ]
