# Generated by Django 5.2.8 on 2026-05-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_photo_cloudinary'),
        ('tenants', '0007_uuid_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stream',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_students', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('tenant', 'name', 'class_label')},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('admission_number__isnull', False)), fields=('tenant', 'admission_number'), name='unique_admission_per_tenant'),
        ),
    ]
