# Generated by Django 5.2.8 on 2026-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_attendance_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('combined', 'Combined School')], default='secondary', max_length=20),
        ),
        migrations.AlterField(
            model_name='stream',
            name='class_label',
            field=models.CharField(blank=True, choices=[('Baby', 'Baby Class'), ('Middle', 'Middle Class'), ('Top', 'Top Class'), ('P.1', 'Primary 1'), ('P.2', 'Primary 2'), ('P.3', 'Primary 3'), ('P.4', 'Primary 4'), ('P.5', 'Primary 5'), ('P.6', 'Primary 6'), ('P.7', 'Primary 7'), ('S.1', 'Senior 1'), ('S.2', 'Senior 2'), ('S.3', 'Senior 3'), ('S.4', 'Senior 4'), ('S.5', 'Senior 5'), ('S.6', 'Senior 6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_assigned',
            field=models.CharField(blank=True, choices=[('Baby', 'Baby Class'), ('Middle', 'Middle Class'), ('Top', 'Top Class'), ('P.1', 'Primary 1'), ('P.2', 'Primary 2'), ('P.3', 'Primary 3'), ('P.4', 'Primary 4'), ('P.5', 'Primary 5'), ('P.6', 'Primary 6'), ('P.7', 'Primary 7'), ('S.1', 'Senior 1'), ('S.2', 'Senior 2'), ('S.3', 'Senior 3'), ('S.4', 'Senior 4'), ('S.5', 'Senior 5'), ('S.6', 'Senior 6')], max_length=10),
        ),
    ]
