# Generated by Django 5.2.8 on 2026-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_generatedreport_secure_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmark',
            old_name='ca_score',
            new_name='a1_score',
        ),
        migrations.RenameField(
            model_name='studentmark',
            old_name='exam_score',
            new_name='a2_score',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='a3_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
