import os
import requests
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / '.env')

api_key = os.getenv('GEMINI_API_KEY')
print(f"Gemini API Key loaded: {'YES' if api_key else 'NO'}")
print(f"Key preview: {api_key[:20]}..." if api_key else "No key found")

# Test Gemini directly
print("\n--- Testing Gemini API ---")
try:
    response = requests.post(
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent",
        headers={"Content-Type": "application/json", "X-goog-api-key": api_key},
        json={"contents": [{"parts": [{"text": "Say only: Gemini connection successful"}]}]},
        timeout=15
    )
    if response.status_code == 200:
        text = response.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
        print(f"Gemini says: {text}")
        print("[PASS] Gemini is working!")
    else:
        print(f"[FAIL] Status {response.status_code}: {response.text}")
        exit(1)
except Exception as e:
    print(f"[FAIL] Error: {e}")
    exit(1)

# Test ai_comments service
print("\n--- Testing ai_comments service ---")
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))

from ai_comments.services import generate_ai_comment

comment, used_ai = generate_ai_comment(
    student_name="John Doe",
    overall_score=78.5,
    subject_performance={
        "Mathematics": {"score": 85, "grade": "B"},
        "English":     {"score": 72, "grade": "C"},
        "Science":     {"score": 78, "grade": "B"},
    },
    term="Term 1",
    academic_year="2025"
)

print(f"Generated by AI : {used_ai}")
print(f"Comment: {comment}")
