# Generated by Django 5.2.8 on 2026-01-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('po_box', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobilemoney', 'Mobile Money'), ('debt', 'Debt')], max_length=20)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_partial_payment_method', models.CharField(blank=True, max_length=20)),
                ('debt_partial_mobile_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('cart_source', models.CharField(choices=[('user', 'User Cart'), ('admin_manual', 'Admin Manual Entry')], default='user', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abandoned Cart',
                'verbose_name_plural': 'Abandoned Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price_type', models.CharField(default='retail', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.abandonedcart')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('participant', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('reminder_minutes_before', models.IntegerField(default=30)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recurrence_until', models.DateField(blank=True, null=True)),
                ('recurrence_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='invited', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.appointment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('retail', 'Retail / Shop'), ('wholesale', 'Wholesale / Distribution'), ('supermarket', 'Supermarket / Grocery'), ('restaurant', 'Restaurant / Food & Beverage'), ('manufacturing', 'Manufacturing'), ('services', 'Service Business'), ('healthcare', 'Health / Medical'), ('school', 'Education / School'), ('agrobusiness', 'Agriculture / Agribusiness'), ('hardware', 'Hardware / Construction'), ('transportation', 'Transportation / Logistics'), ('ecommerce', 'E-commerce / Online Business'), ('nonprofit', 'Non-Profit / NGO'), ('other', 'Other')], default='other', help_text='Used only for applying initial presets. Does NOT control app behavior.', max_length=50)),
                ('industry_description', models.TextField(blank=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('preset_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Business Configuration',
                'verbose_name_plural': 'Business Configurations',
            },
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('dashboard_enabled', 'Dashboard'), ('organizations_enabled', 'My Organizations'), ('product_enabled', 'Products/Services'), ('inventory_enabled', 'Inventory Management'), ('orders_enabled', 'Orders/Transactions'), ('customers_enabled', 'Customers/Contacts'), ('scheduling_enabled', 'Scheduling & Appointments'), ('manual_entry_enabled', 'Manual Entry'), ('payments_enabled', 'Payments & Receipts'), ('partial_payments_enabled', 'Partial Payments'), ('approval_required', 'Approval Workflow'), ('delivery_enabled', 'Delivery Management'), ('batch_tracking', 'Batch/Lot Tracking'), ('expiry_tracking', 'Expiry Date Tracking'), ('analytics_enabled', 'Analytics'), ('ai_insights_enabled', 'AI Insights'), ('accounting_enabled', 'Accounting'), ('enrollment_enabled', 'Enrollment'), ('multi_location', 'Multi-Location Support'), ('customer_portal', 'Customer Portal'), ('supplier_management', 'Supplier Management'), ('loyalty_program', 'Loyalty Program'), ('advanced_analytics', 'Advanced Analytics')], help_text='Feature identifier used in code', max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this feature is enabled')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggles', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=200)),
                ('order_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=10)),
                ('order_source', models.CharField(choices=[('user', 'User Order'), ('manual', 'Manual Order')], default='user', max_length=10)),
                ('delivery', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abandonedcart',
            name='converted_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_from_cart', to='core.order'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('country', models.CharField(default='UG', max_length=5)),
                ('wholesale_threshold', models.IntegerField(default=10)),
                ('price_priority', models.CharField(choices=[('retail-first', 'Retail first'), ('wholesale-first', 'Wholesale first'), ('country-first', 'Country first')], default='retail-first', max_length=32)),
                ('wholesale_availability', models.JSONField(default=list, help_text='List of roles allowed: everyone, wholesalers, assigned')),
                ('enable_tax', models.BooleanField(default=False)),
                ('tax_mode', models.CharField(choices=[('included', 'Tax included'), ('added', 'Tax added at checkout')], default='included', max_length=20)),
                ('price_missing', models.CharField(choices=[('default', 'Allow zero price'), ('block', 'Block add to cart'), ('hide', 'Hide product')], default='default', max_length=20)),
                ('rounding', models.CharField(choices=[('nearest', 'Round to nearest'), ('up', 'Round up'), ('down', 'Round down')], default='nearest', max_length=20)),
                ('order_limit_min', models.IntegerField(default=1)),
                ('order_limit_max', models.IntegerField(default=99999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price_type', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_debt', models.BooleanField(default=False)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.receipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Terminology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('resource', 'Resource (Product/Service/Subject)'), ('transaction', 'Transaction (Order/Visit/Enrollment)'), ('entity', 'Entity (Customer/Patient/Student)'), ('inventory', 'Inventory (Stock/Supplies)'), ('payment', 'Payment'), ('schedule', 'Schedule (Appointment/Session)'), ('location', 'Location (Branch/Facility)')], help_text='Internal generic entity name', max_length=50)),
                ('label', models.CharField(help_text='Business-specific singular label (e.g., "Product", "Patient")', max_length=100)),
                ('label_plural', models.CharField(help_text='Business-specific plural label (e.g., "Products", "Patients")', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminology', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Terminology',
                'verbose_name_plural': 'Terminology',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('color', models.CharField(default='#3B82F6', help_text='Primary color identifier used to lookup full palette', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='WorkerAccessInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(db_index=True, max_length=12)),
                ('otp_expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('allowed_pages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_invites', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Worker Access Invite',
                'verbose_name_plural': 'Worker Access Invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_pages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_access_controls', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Page Access',
                'verbose_name_plural': 'Worker Page Access',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_time'], name='core_appoin_start_t_088d11_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='core_appoin_status_e978b8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_to'], name='core_appoin_assigne_a7799c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentattendee',
            unique_together={('appointment', 'email')},
        ),
        migrations.AddIndex(
            model_name='featuretoggle',
            index=models.Index(fields=['tenant', 'feature_key'], name='core_featur_tenant__3996e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featuretoggle',
            unique_together={('tenant', 'feature_key')},
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['-created_at'], name='core_abando_created_fda50d_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['cart_source'], name='core_abando_cart_so_f1de3c_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['recovered'], name='core_abando_recover_612ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='terminology',
            index=models.Index(fields=['tenant', 'entity'], name='core_termin_tenant__5ca9e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminology',
            unique_together={('tenant', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='workeraccessinvite',
            unique_together={('tenant', 'email')},
        ),
    ]
