# Generated by Django 5.2.8 on 2026-04-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receipt_tenant_fk'),
        ('tenants', '0007_uuid_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenants.tenant'),
        ),
    ]
