# Generated by Django 5.2.8 on 2026-04-30 16:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
