# Generated by Django 5.2.8 on 2026-05-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cloudinary_theme_logo'),
        ('tenants', '0007_uuid_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='tenants.tenant'),
        ),
    ]
