# Generated by Django 5.2.8 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenant_aware_business_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='motto',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
