# Generated by Django 5.2.8 on 2026-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_motto_to_business_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeraccessinvite',
            name='school_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workeraccessinvite',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
