# Generated by Django 5.2.8 on 2026-05-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_username_role_to_worker_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='staff_credentials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
