# Generated by Django 5.2.8 on 2026-05-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
