# Generated by Django 5.2.8 on 2026-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='custom_category',
            field=models.CharField(blank=True, help_text='Used when payment_category is "other"', max_length=100),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_category',
            field=models.CharField(choices=[('school_fees', 'School Fees'), ('uneb_registration', 'UNEB Registration'), ('ple_registration', 'PLE Registration'), ('transport', 'Transport'), ('meals', 'Meals / Boarding'), ('uniform', 'Uniform'), ('books', 'Books & Stationery'), ('medical', 'Medical'), ('sports', 'Sports & Activities'), ('other', 'Other')], default='school_fees', max_length=50),
        ),
    ]
