# Generated by Django 5.2.8 on 2026-05-04 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feepayment_custom_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_mode', models.CharField(blank=True, default='', max_length=10)),
                ('sig_image', models.TextField(blank=True)),
                ('sig_name', models.CharField(blank=True, max_length=200)),
                ('stamp_raw', models.TextField(blank=True)),
                ('stamp_offset_x', models.IntegerField(default=0)),
                ('stamp_offset_y', models.IntegerField(default=0)),
                ('stamp_rotate', models.IntegerField(default=0)),
                ('stamp_circular', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
