# Generated by Django 5.2.8 on 2026-05-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_receiptsettings_sig_label'),
        ('tenants', '0007_uuid_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('tenant', 'class_assigned', 'term', 'academic_year')},
        ),
    ]
