# Generated by Django 5.2.8 on 2026-05-06 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_tenant_isolation'),
        ('students', '0013_attendance_model'),
        ('tenants', '0007_uuid_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feestructure')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeItemPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='fees.feeitem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_payments', to='fees.feepayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_payments', to='students.student')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('student', 'item')},
            },
        ),
    ]
