# Generated by Django 5.2.8 on 2026-05-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_feepayment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
