# Generated by Django 5.2.8 on 2026-01-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail / Shop'), ('wholesale', 'Wholesale / Distribution'), ('supermarket', 'Supermarket / Grocery'), ('restaurant', 'Restaurant / Food & Beverage'), ('manufacturing', 'Manufacturing'), ('services', 'Service Business'), ('healthcare', 'Health / Medical'), ('school', 'Education / School'), ('agrobusiness', 'Agriculture / Agribusiness'), ('hardware', 'Hardware / Construction'), ('transportation', 'Transportation / Logistics'), ('ecommerce', 'E-commerce / Online Business'), ('nonprofit', 'Non-Profit / NGO'), ('other', 'Other')], default='other', help_text='Type of business for this tenant (controls auto-configuration)', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Tenant account must be verified to access system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.JSONField(default=dict)),
                ('fields', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
