# Generated by Django 5.2.8 on 2026-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain_url',
            field=models.CharField(blank=True, help_text='Domain URL for tenant (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(blank=True, help_text='Schema name for multi-tenancy (optional)', max_length=64, null=True),
        ),
    ]
