# Generated by Django 5.2.8 on 2026-01-22 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_domain_url_tenant_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique tenant ID', null=True, blank=True),
        ),
    ]
