# Generated by Django 5.2.8 on 2026-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Globally unique tenant ID', null=True),
        ),
    ]
