# Generated by Django 5.2.8 on 2026-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_populate_tenant_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(default=1, editable=False, help_text='Globally unique tenant ID', unique=True),
            preserve_default=False,
        ),
    ]
