# Generated by Django 5.2.8 on 2026-04-28 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique tenant ID', unique=True),
        ),
    ]
