# Generated by Django 5.2.8 on 2026-05-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_uuid_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='school_role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies (DOS)'), ('deputy', 'Deputy Headteacher'), ('headteacher', 'Headteacher'), ('director', 'Director')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
