# Generated by Django 5.2.8 on 2026-05-07 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_add_worker_school_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('building', 'Building'), ('land', 'Land'), ('furniture', 'Furniture'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle'), ('computer', 'Computer/IT Equipment'), ('other', 'Other Asset')], max_length=20)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation %', max_digits=5)),
                ('condition', models.CharField(blank=True, help_text='Good, Fair, Poor', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'School Asset',
                'verbose_name_plural': 'School Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(help_text='Who we owe', max_length=200)),
                ('debt_type', models.CharField(choices=[('supplier', 'Supplier Debt'), ('loan', 'Bank Loan'), ('salary', 'Unpaid Salaries'), ('utility', 'Utility Bills'), ('rent', 'Rent Arrears'), ('other', 'Other Debt')], max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue')], default='active', max_length=20)),
                ('incurred_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_debts_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_debts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'School Debt',
                'verbose_name_plural': 'School Debts',
                'ordering': ['-incurred_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('salaries', 'Teacher Salaries'), ('utilities', 'Utilities (Water, Electricity)'), ('supplies', 'School Supplies'), ('maintenance', 'Maintenance & Repairs'), ('transport', 'Transport'), ('food', 'Food & Catering'), ('equipment', 'Equipment'), ('rent', 'Rent'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_expense_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'School Expense Category',
                'verbose_name_plural': 'School Expense Categories',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('payee', models.CharField(help_text='Who was paid', max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_expenses', to='tenants.tenant')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='school_accounting.schoolexpensecategory')),
            ],
            options={
                'verbose_name': 'School Expense',
                'verbose_name_plural': 'School Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('income_type', models.CharField(choices=[('fees', 'School Fees'), ('donation', 'Donation'), ('grant', 'Government Grant'), ('fundraising', 'Fundraising'), ('other', 'Other Income')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(help_text='Who paid/donated', max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_income_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_income', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'School Income',
                'verbose_name_plural': 'School Income',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('month', models.DateField(help_text='Month for which salary is paid')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, help_text='Transport, housing, etc.', max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Tax, NSSF, etc.', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_salaries_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Teacher Salary',
                'verbose_name_plural': 'Teacher Salaries',
                'ordering': ['-month', 'teacher_name'],
                'unique_together': {('tenant', 'teacher_name', 'month')},
            },
        ),
    ]
