# Generated by Django 5.2.8 on 2026-05-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_accounting', '0002_salary_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreceipt',
            name='secure_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
