# Generated by Django 5.2.8 on 2026-05-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_gradingsystem_subject_competency_assessment_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_comment', to='enrollment.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comments', to='enrollment.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
    ]
