# Generated by Django 5.2.8 on 2026-05-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_comments', '0001_initial'),
        ('students', '0013_attendance_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireportcomment',
            name='report',
        ),
        migrations.AddField(
            model_name='aireportcomment',
            name='report_snapshot_id',
            field=models.IntegerField(blank=True, help_text='ID of the GeneratedReport this comment belongs to', null=True),
        ),
        migrations.AlterField(
            model_name='aireportcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comments', to='students.student'),
        ),
    ]
