# Generated by Django 5.2.8 on 2026-05-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('tenants', '0007_uuid_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_boundaries', models.JSONField(default=dict, help_text='Grade boundaries mapping. Default: {A: 80, B: 70, C: 60, D: 50, E: 40, F: 0}')),
                ('remarks', models.JSONField(default=dict, help_text='Grade remarks. Default: {A: "Exceptional", B: "Outstanding", ...}')),
                ('excellent_threshold', models.FloatField(default=80, help_text='Score threshold for "Excellent" performance')),
                ('good_threshold', models.FloatField(default=70, help_text='Score threshold for "Good" performance')),
                ('average_threshold', models.FloatField(default=60, help_text='Score threshold for "Average" performance')),
                ('weak_threshold', models.FloatField(default=50, help_text='Score threshold for "Needs Improvement"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Tenant that owns this grading system', on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Subject code (e.g., MATH01, ENG01)', max_length=20)),
                ('name', models.CharField(help_text='Subject name (e.g., Mathematics, English)', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_or_grade', models.CharField(help_text='Class/Grade (e.g., Primary 5, Form 2, Year 10)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='School/Institution (Tenant) that owns this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Competency code (e.g., COMP01)', max_length=20)),
                ('name', models.CharField(help_text='Competency name/description', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('weighting', models.FloatField(default=1.0, help_text='Weight/importance of this competency (for weighted calculations)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Subject this competency belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='enrollment.subject')),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('ca', 'Continuous Assessment (CA)'), ('exam', 'Exam'), ('practical', 'Practical'), ('project', 'Project'), ('participation', 'Participation')], default='ca', help_text='Type of assessment', max_length=20)),
                ('score', models.FloatField(help_text='Assessment score (0-100)')),
                ('out_of', models.FloatField(default=100, help_text='Total marks for this assessment')),
                ('term', models.CharField(help_text='Term/Semester (e.g., Term 1, Semester 1, Q1)', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024, 2024-2025)', max_length=20)),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Assessment notes/comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='enrollment.student')),
                ('competency', models.ForeignKey(blank=True, help_text='Specific competency assessed (optional, can be null for overall subject scores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='enrollment.competency')),
                ('subject', models.ForeignKey(help_text='Subject being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='enrollment.subject')),
            ],
            options={
                'ordering': ['-date_assessed', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Term/Semester (e.g., Term 1)', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year', max_length=20)),
                ('overall_score', models.FloatField(help_text='Overall average score')),
                ('overall_grade', models.CharField(choices=[('A', 'Exceptional / Distinction'), ('B', 'Outstanding'), ('C', 'Satisfactory'), ('D', 'Basic'), ('E', 'Elementary / Below Expected'), ('F', 'Fail')], max_length=2)),
                ('overall_remark', models.CharField(max_length=100)),
                ('subject_performance', models.JSONField(default=dict, help_text='Aggregated scores/grades per subject: {subject_code: {score, grade, remark, competencies: []}}')),
                ('teacher_comment', models.TextField(blank=True, help_text='Auto-generated or manual teacher comment', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student whose report this is', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='enrollment.student')),
            ],
            options={
                'ordering': ['-academic_year', '-term'],
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='enrollment__student_7b85b4_idx')],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['tenant', 'is_active'], name='enrollment__tenant__d339f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('tenant', 'code', 'class_or_grade')},
        ),
        migrations.AlterUniqueTogether(
            name='competency',
            unique_together={('subject', 'code')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['student', 'subject', 'term'], name='enrollment__student_d1e69d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['student', 'academic_year'], name='enrollment__student_ca93a3_idx'),
        ),
    ]
