# Generated by Django 5.2.8 on 2026-01-22 12:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.PositiveSmallIntegerField()),
                ('baseline', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('recent_trend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sector_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('scarcity_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('universal_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('salary_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('forecast_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('restock_required', models.BooleanField(default=False)),
                ('restock_window', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_increase_hints', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecast.business')),
            ],
            options={
                'ordering': ['business', 'target_month'],
                'unique_together': {('business', 'target_month')},
            },
        ),
    ]
