# Generated by Django 5.2.8 on 2026-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='suggested_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
