# Generated by Django 5.2.8 on 2026-04-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecast_suggested_products'),
        ('tenants', '0007_uuid_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='tenants.tenant'),
        ),
    ]
