# Generated by Django 5.2.8 on 2026-01-18 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('current', 'Current Asset'), ('fixed', 'Fixed Asset'), ('intangible', 'Intangible Asset')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation rate (%)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('print', 'Print')], max_length=20)),
                ('model_type', models.CharField(choices=[('expense', 'Expense'), ('payment', 'Payment'), ('tax', 'Tax'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('expense_category', 'Expense Category')], max_length=30)),
                ('object_id', models.IntegerField(help_text='ID of the record affected')),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=500)),
                ('changes', models.JSONField(blank=True, help_text='JSON of changes made (before/after)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint accessed', max_length=200)),
                ('method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE)', max_length=10)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged for unusual activity')),
                ('notes', models.TextField(blank=True, help_text='Additional context or flags')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_type', models.CharField(choices=[('capital', 'Owner Capital'), ('retained_earnings', 'Retained Earnings'), ('draws', 'Owner Draws')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equity',
                'verbose_name_plural': 'Equity',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('liability_type', models.CharField(choices=[('current', 'Current Liability'), ('long_term', 'Long-term Liability')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('party_name', models.CharField(help_text='Payee or Payer name', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tax name (e.g., VAT Standard Rate)', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Unique tax code (e.g., VAT-18%)', max_length=50)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('income_tax', 'Income Tax'), ('payroll_tax', 'Payroll Tax'), ('sales_tax', 'Sales Tax'), ('property_tax', 'Property Tax'), ('withholding_tax', 'Withholding Tax'), ('excise_duty', 'Excise Duty'), ('import_duty', 'Import Duty'), ('other', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('direct', 'Direct Tax'), ('indirect', 'Indirect Tax')], default='indirect', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate in percentage', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('due', 'Due'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('filed', 'Filed')], default='due', max_length=20)),
                ('period_start', models.DateField(help_text='Tax period start date')),
                ('period_end', models.DateField(help_text='Tax period end date')),
                ('effective_date', models.DateField(blank=True, help_text='Date when tax becomes effective', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when tax expires', null=True)),
                ('apply_to_products', models.BooleanField(default=True, help_text='Apply to products')),
                ('apply_to_services', models.BooleanField(default=True, help_text='Apply to services')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this tax mandatory')),
                ('is_compound', models.BooleanField(default=False, help_text='Is this a compound/multi-tier tax')),
                ('notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of this tax')),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('filing_reminder_days', models.IntegerField(default=7, help_text='Days before due date to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'ordering': ['-due_date'],
            },
        ),
    ]
